### ISSUE TITLE
doesn't find 🥊 (Boxing glove)

### ISSUE THREAD

**Issue by hirasso** [urakozz/php-emoji-regex#2]
Hi there, just testing your neat little class – it seems not to be able to find the boxing glove emoji. Could it be possible that you've missed it?

https://www.compart.com/de/unicode/U+1F94A

**Comment by YAGrand** [comment]
> Hi there, just testing your neat little class – it seems not to be able to find the boxing glove emoji. Could it be possible that you've missed it?
> 
> https://www.compart.com/de/unicode/U+1F94A

Im added all new emoji codes, use this fork https://github.com/YAGrand/php-emoji-regex

**Comment by urakozz** [comment]
@YAGrand thx for the update, but one test is failing, do you have any ideas why? (https://github.com/urakozz/php-emoji-regex/pull/3)

**Comment by YAGrand** [comment]
> @YAGrand thx for the update, but one test is failing, do you have any ideas why? (#3)

What a test, did u have dump? Server config?

For me its working 
![screenshot_130](https://user-images.githubusercontent.com/11403132/53742042-c90cd500-3ea8-11e9-82a2-b7ffbf6da21e.jpg)

**Comment by urakozz** [comment]
Ну едрить, там unit тесты в комплекте ))
https://travis-ci.org/urakozz/php-emoji-regex/jobs/501537776
@YAGrand  ^^

**Comment by YAGrand** [comment]
> Ну едрить, там unit тесты в комплекте ))
> https://travis-ci.org/urakozz/php-emoji-regex/jobs/501537776
> @YAGrand ^^

Проверяй, там код решётки попал в регулярку, сейчас на это не будет ругаться
