### ISSUE TITLE
Version 0.1.0 matches/replaces numbers

### ISSUE THREAD

**Issue by adamgorski** [urakozz/php-emoji-regex#4]
The updated version of the regex in version 0.1.0 (compared to 0.0.2) matches and thus replaces numbers in the target string. Looking at the regex itself, I see the patterns `\\x{0031}\\    x{0032}\\x{0033}\\x{0034}\\x{0035}\\x{0036}\\x{0037}\\x{0038}\\x{0039}\\x{0030}` which, if I'm reading them correctly, are in fact the hex codes for numbers. Is this on purpose for some reason, or is it a bug?

Thanks!

**Comment by ventormo** [comment]
I also ran into this problem, a line like `88001234567` is perceived as emoji.

@urakozz any comments, please? 

I could fix it by checking for a regular expression of 0-9, but I'm not sure if this is a good idea. Maybe it would be better to do as @adamgorski suggested?

**Comment by adamgorski** [comment]
I think the fix is to just remove those hex codes from the match string in the library. My guess is that it was put in there by mistake with the last update and not caught by any tests.

**Comment by urakozz** [comment]
TBH I don't even remember how I wrote it initially and I don't even write php last 4 years. In release was added support for the new and colorful emoji, it could happen there is a bug there. You can try to investigate and send me a pull request)
